version: '2.0'

services:
  api:
      build: .
      ports: 
        - "3000:3000"
      volumes:
        - .:/app
      depends_on:
        - db
  db:
      image: "mongo"
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db
      